# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 12:57
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tony', max_length=20)),
                ('national_id', models.IntegerField(default='23456789')),
                ('phone', models.IntegerField(default='0723456756', null=True)),
                ('email', models.CharField(blank=True, default='abc@gmail.com', max_length=50)),
                ('postal_address', models.IntegerField(blank=True, default='07-00902')),
                ('status', models.CharField(choices=[('In Business', 'In business'), ('For Sale', 'For Sale')], default='for rent', max_length=50)),
                ('opening_days', models.CharField(default='monday to friday', max_length=50)),
                ('opening', models.IntegerField(default='0700')),
                ('closing', models.IntegerField(default='1700')),
                ('address', models.CharField(default='Moringa School', max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=50)),
                ('county', models.CharField(default='Nairobi', max_length=50)),
                ('city', models.CharField(default='Nairobi', max_length=50)),
                ('town', models.CharField(default='Nakuru', max_length=50)),
                ('village', models.CharField(blank=True, default='mamba', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('description', models.TextField(default='The best', max_length=1000)),
                ('company', models.CharField(default='johnsons family business', max_length=20)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image1', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image2', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image3', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image4', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image5', pyuploadcare.dj.models.ImageField(blank=True)),
                ('posting_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Construction Material Hardware', 'construction material hardware'), ('Foods', 'foods'), ('Supermarkets', 'supermarkets'), ('Restaurants ', 'restaurants'), ('Botique', 'botique'), ('Bars', 'bars'), ('Bookshop', 'bookshop'), ('Hospitals', 'hospitals'), ('Electric Hardware', 'electric hardware')], default='Hotel', max_length=100)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('commented_on', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='life.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tony', max_length=20)),
                ('national_id', models.IntegerField(default='23456789')),
                ('phone', models.IntegerField(default='0723456756', null=True)),
                ('email', models.CharField(blank=True, default='abc@gmail.com', max_length=50)),
                ('postal_address', models.IntegerField(blank=True, default='07-00902')),
                ('status', models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale')], default='for rent', max_length=50)),
                ('opening_days', models.CharField(default='monday to friday', max_length=50)),
                ('opening', models.IntegerField(default='0700')),
                ('closing', models.IntegerField(default='1700')),
                ('address', models.CharField(default='Moringa School', max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=50)),
                ('county', models.CharField(default='Nairobi', max_length=50)),
                ('city', models.CharField(default='Nairobi', max_length=50)),
                ('town', models.CharField(default='Nakuru', max_length=50)),
                ('village', models.CharField(blank=True, default='mamba', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('description', models.TextField(default='The Best', max_length=10000)),
                ('company', models.CharField(default='Five star apartments', max_length=20)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image1', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image2', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image3', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image4', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image5', pyuploadcare.dj.models.ImageField(blank=True)),
                ('posting_date', models.DateTimeField(auto_now=True)),
                ('size', models.IntegerField(default='10*10')),
                ('firnished', models.BooleanField(default=False)),
                ('unfirnished', models.BooleanField(default=False)),
                ('amenities', models.CharField(choices=[(' Good Road', 'Good Road'), ('Electricity', 'Electricity'), ('Hospital', 'Hospital'), ('School', 'School'), ('Water', 'Water'), ('Security', 'Security')], default='security', max_length=50)),
                ('price', models.IntegerField(default='100', null=True)),
                ('mode_of_payment', models.CharField(choices=[('Paypal', 'Paypal'), ('M-pesa', 'M-pesa')], default='m-pesa', max_length=50)),
                ('category', models.CharField(choices=[('Mansionette', 'mansionette'), ('Town Houses', 'town houses'), ('Studio ', 'studio'), ('Single Rooms', 'single rooms'), ('Bedsitters', 'bedsitters'), ('Container Houses', 'container houses'), ('Rooms', 'rooms'), ('Flats and Apartments', 'flats and apartments'), ('Houses', 'houses'), ('Bungalows', 'bungalows'), ('Hostels', 'hostels')], default='appartment', max_length=100)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tony', max_length=20)),
                ('pic', pyuploadcare.dj.models.ImageField(blank=True)),
                ('bio', models.CharField(default='Hi!', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tony', max_length=20)),
                ('national_id', models.IntegerField(default='23456789')),
                ('phone', models.IntegerField(default='0723456756', null=True)),
                ('email', models.CharField(blank=True, default='abc@gmail.com', max_length=50)),
                ('postal_address', models.IntegerField(blank=True, default='07-00902')),
                ('status', models.CharField(choices=[('In Business', 'In business'), ('For Sale', 'For Sale')], default='for rent', max_length=50)),
                ('opening_days', models.CharField(default='monday to friday', max_length=50)),
                ('opening', models.IntegerField(default='0700')),
                ('closing', models.IntegerField(default='1700')),
                ('address', models.CharField(default='Moringa School', max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=50)),
                ('county', models.CharField(default='Nairobi', max_length=50)),
                ('city', models.CharField(default='Nairobi', max_length=50)),
                ('town', models.CharField(default='Nakuru', max_length=50)),
                ('village', models.CharField(blank=True, default='mamba', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('description', models.TextField(default='The best', max_length=1000)),
                ('company', models.CharField(default='Cheap and fast enterprise', max_length=20)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image1', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image2', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image3', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image4', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image5', pyuploadcare.dj.models.ImageField(blank=True)),
                ('posting_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Phone repair', 'phone repair'), ('Car Tracking', 'car tracking'), ('Photographer', 'photographer'), ('Barber', 'barber'), ('Lawyers', 'lawyers'), ('Vehicle Branding', 'vehicle branding'), ('Massage', 'massage'), ('Cyber', 'cyber'), ('Church,Mosque', 'church,mosque'), ('Electrician', 'Electrician'), ('Gardener', 'gardener'), ('Saloon', 'saloon'), ('T-shirt Printing', 'T-shirt Printing'), ('House maid service', 'house maid service'), ('Kibanda foods', 'kibanda foods'), ('Water point', 'water point'), ('Spa', 'spa'), ('Library', 'library'), ('Shoe repair', 'shoe repair'), ('Swimming Pool maintenance', 'swimming pool maintenance'), ('Fencing service', 'fencing service'), ('Security Guard', 'security guard'), ('Plumber', 'plumber')], default='plumber', max_length=100)),
                ('price', models.IntegerField(default='100', null=True)),
                ('available', models.BooleanField(default=False)),
                ('meeting_point', models.CharField(default='greenhouse', max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('owner_name', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='life.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='housing',
            name='owner_name',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housing', to='life.Profile'),
        ),
        migrations.AddField(
            model_name='comments',
            name='housing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='life.Housing'),
        ),
        migrations.AddField(
            model_name='comments',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='life.Services'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='life.Profile'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_name',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='life.Profile'),
        ),
    ]
