# Generated by Django 2.2.4 on 2019-08-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Restaurants ', 'restaurants'), ('Hospitals', 'hospitals'), ('Foods', 'foods'), ('Electric Hardware', 'electric hardware'), ('Supermarkets', 'supermarkets'), ('Bookshop', 'bookshop'), ('Botique', 'botique'), ('Bars', 'bars'), ('Construction Material Hardware', 'construction material hardware')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='category',
            field=models.CharField(choices=[('Bedsitters', 'bedsitters'), ('Houses', 'houses'), ('Single Rooms', 'single rooms'), ('Town Houses', 'town houses'), ('Rooms', 'rooms'), ('Hostels', 'hostels'), ('Bungalows', 'bungalows'), ('Flats and Apartments', 'flats and apartments'), ('Studio ', 'studio')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='available',
            field=models.CharField(choices=[('NO', 'no'), ('YES', 'yes')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Phone repair', 'phone repair'), ('Water point', 'water point'), ('Saloon', 'saloon'), ('Spa', 'spa'), ('Library', 'library'), ('Barber', 'barber'), ('Massage', 'massage'), ('Kibanda foods', 'kibanda foods'), ('Shoe repair', 'shoe repair')], max_length=1000),
        ),
    ]
