# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Foods', 'foods'), ('Restaurants ', 'restaurants'), ('Electric Hardware', 'electric hardware'), ('Bookshop', 'bookshop'), ('Botique', 'botique'), ('Hospitals', 'hospitals'), ('Supermarkets', 'supermarkets'), ('Construction Material Hardware', 'construction material hardware'), ('Bars', 'bars')], default='Hotel', max_length=100),
        ),
        migrations.AlterField(
            model_name='housing',
            name='amenities',
            field=models.CharField(choices=[('Hospital', 'Hospital'), (' Good Road', 'Good Road'), ('Electricity', 'Electricity'), ('Water', 'Water'), ('Security', 'Security'), ('School', 'School')], default='security', max_length=50),
        ),
        migrations.AlterField(
            model_name='housing',
            name='category',
            field=models.CharField(choices=[('Houses', 'houses'), ('Rooms', 'rooms'), ('Bedsitters', 'bedsitters'), ('Mansionette', 'mansionette'), ('Town Houses', 'town houses'), ('Flats and Apartments', 'flats and apartments'), ('Bungalows', 'bungalows'), ('Hostels', 'hostels'), ('Container Houses', 'container houses'), ('Single Rooms', 'single rooms'), ('Studio ', 'studio')], default='appartment', max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Spa', 'spa'), ('Photographer', 'photographer'), ('Barber', 'barber'), ('Cyber', 'cyber'), ('Swimming Pool maintenance', 'swimming pool maintenance'), ('Water point', 'water point'), ('Gardener', 'gardener'), ('Saloon', 'saloon'), ('Car Tracking', 'car tracking'), ('Security Guard', 'security guard'), ('Shoe repair', 'shoe repair'), ('Lawyers', 'lawyers'), ('Vehicle Branding', 'vehicle branding'), ('Fencing service', 'fencing service'), ('Kibanda foods', 'kibanda foods'), ('Massage', 'massage'), ('Electrician', 'Electrician'), ('Plumber', 'plumber'), ('Phone repair', 'phone repair'), ('Library', 'library'), ('House maid service', 'house maid service'), ('Church,Mosque', 'church,mosque'), ('T-shirt Printing', 'T-shirt Printing')], default='plumber', max_length=100),
        ),
    ]
