# Generated by Django 2.2.4 on 2019-08-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20190828_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='life.User'),
        ),
        migrations.AddField(
            model_name='housing',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='life.User'),
        ),
        migrations.AddField(
            model_name='services',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='life.User'),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Restaurants ', 'restaurants'), ('Hospitals', 'hospitals'), ('Bars', 'bars'), ('Electric Hardware', 'electric hardware'), ('Supermarkets', 'supermarkets'), ('Construction Material Hardware', 'construction material hardware'), ('Bookshop', 'bookshop'), ('Foods', 'foods'), ('Botique', 'botique')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='category',
            field=models.CharField(choices=[('Studio ', 'studio'), ('Hostels', 'hostels'), ('Town Houses', 'town houses'), ('Flats and Apartments', 'flats and apartments'), ('Rooms', 'rooms'), ('Bedsitters', 'bedsitters'), ('Single Rooms', 'single rooms'), ('Houses', 'houses'), ('Bungalows', 'bungalows')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='available',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Kibanda foods', 'kibanda foods'), ('Massage', 'massage'), ('Saloon', 'saloon'), ('Shoe repair', 'shoe repair'), ('Water point', 'water point'), ('Phone repair', 'phone repair'), ('Barber', 'barber'), ('Spa', 'spa'), ('Library', 'library')], max_length=1000),
        ),
    ]
