# Generated by Django 2.2.4 on 2019-08-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_auto_20190828_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='owner_id',
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Foods', 'foods'), ('Supermarkets', 'supermarkets'), ('Hospitals', 'hospitals'), ('Construction Material Hardware', 'construction material hardware'), ('Bars', 'bars'), ('Bookshop', 'bookshop'), ('Electric Hardware', 'electric hardware'), ('Restaurants ', 'restaurants'), ('Botique', 'botique')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='category',
            field=models.CharField(choices=[('Hostels', 'hostels'), ('Studio ', 'studio'), ('Bedsitters', 'bedsitters'), ('Rooms', 'rooms'), ('Houses', 'houses'), ('Single Rooms', 'single rooms'), ('Bungalows', 'bungalows'), ('Town Houses', 'town houses'), ('Flats and Apartments', 'flats and apartments')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Saloon', 'saloon'), ('Kibanda foods', 'kibanda foods'), ('Library', 'library'), ('Spa', 'spa'), ('Water point', 'water point'), ('Shoe repair', 'shoe repair'), ('Massage', 'massage'), ('Phone repair', 'phone repair'), ('Barber', 'barber')], max_length=1000),
        ),
    ]
