# Generated by Django 2.2.4 on 2019-08-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_auto_20190824_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='closing',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wenesday', 'wenesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='1800', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='opening',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wenesday', 'wenesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='0800', max_length=20),
        ),
        migrations.AddField(
            model_name='housing',
            name='closing',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wenesday', 'wenesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='1800', max_length=20),
        ),
        migrations.AddField(
            model_name='housing',
            name='opening',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wenesday', 'wenesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='0800', max_length=20),
        ),
        migrations.AddField(
            model_name='services',
            name='closing',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wenesday', 'wenesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='1800', max_length=20),
        ),
        migrations.AddField(
            model_name='services',
            name='meeting',
            field=models.CharField(default='greenhouse', max_length=50),
        ),
        migrations.AddField(
            model_name='services',
            name='opening',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wenesday', 'wenesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='0800', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Bookshop', 'bookshop'), ('Foods', 'foods'), ('Construction Material Hardware', 'construction material hardware'), ('Supermarkets', 'supermarkets'), ('Electric Hardware', 'electric hardware'), ('Bars', 'bars'), ('Botique', 'botique'), ('Hospitals', 'hospitals'), ('Restaurants ', 'restaurants')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='category',
            field=models.CharField(choices=[('Hostels', 'hostels'), ('Bedsitters', 'bedsitters'), ('Studio ', 'studio'), ('Houses', 'houses'), ('Town Houses', 'town houses'), ('Flats and Apartments', 'flats and apartments'), ('Rooms', 'rooms'), ('Single Rooms', 'single rooms'), ('Bungalows', 'bungalows')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='available',
            field=models.CharField(choices=[('NO', 'no'), ('YES', 'yes')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Water point', 'water point'), ('Shoe repair', 'shoe repair'), ('Barber', 'barber'), ('Saloon', 'saloon'), ('Library', 'library'), ('Spa', 'spa'), ('Massage', 'massage'), ('Phone repair', 'phone repair'), ('Kibanda foods', 'kibanda foods')], max_length=1000),
        ),
    ]
