# Generated by Django 2.2.4 on 2019-08-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0004_auto_20190828_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='owner_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='owner_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Foods', 'foods'), ('Bookshop', 'bookshop'), ('Construction Material Hardware', 'construction material hardware'), ('Supermarkets', 'supermarkets'), ('Electric Hardware', 'electric hardware'), ('Bars', 'bars'), ('Restaurants ', 'restaurants'), ('Botique', 'botique'), ('Hospitals', 'hospitals')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='housing',
            name='category',
            field=models.CharField(choices=[('Houses', 'houses'), ('Mansionette', 'mansionette'), ('Bungalows', 'bungalows'), ('Container Houses', 'container houses'), ('Rooms', 'rooms'), ('Single Rooms', 'single rooms'), ('Hostels', 'hostels'), ('Flats and Apartments', 'flats and apartments'), ('Town Houses', 'town houses'), ('Studio ', 'studio'), ('Bedsitters', 'bedsitters')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Saloon', 'saloon'), ('Security Guard', 'security guard'), ('Photographer', 'photographer'), ('Plumber', 'plumber'), ('House maid service', 'house maid service'), ('Vehicle Branding', 'vehicle branding'), ('Water point', 'water point'), ('Shoe repair', 'shoe repair'), ('Massage', 'massage'), ('Swimming Pool maintenance', 'swimming pool maintenance'), ('T-shirt Printing', 'T-shirt Printing'), ('Phone repair', 'phone repair'), ('Barber', 'barber'), ('Gardener', 'gardener'), ('Fencing service', 'fencing service'), ('Kibanda foods', 'kibanda foods'), ('Library', 'library'), ('Cyber', 'cyber'), ('Spa', 'spa'), ('Lawyers', 'lawyers'), ('Car Tracking', 'car tracking'), ('Church,Mosque', 'church,mosque')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
